name = "CombinatorialGames"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CombinatorialGames"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0-rc1"

[[lean_lib]]
name = "CombinatorialGames"
