name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: build
        uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9 # v1.5

      - name: cache docs
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: docbuild/.lake
          key: ${{ runner.os }}-docbuild-${{ hashFiles('lean-toolchain', 'docbuild/lakefile.lean', 'docbuild/lake-manifest.json') }}
          restore-keys: ${{ runner.os }}-docbuild-

      - name: docs
        run: |
          cd docbuild
          MATHLIB_NO_CACHE_ON_UPDATE=1 lake update doc-gen4 CombinatorialGames
          lake build CombinatorialGames:docs

      - name: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4

      - name: upload
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: './docbuild/.lake/build/doc'

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    concurrency:
      group: "pages"
      cancel-in-progress: true

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04
    steps:
      - name: deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        id: deployment
